name: Run PHPUnit Tests

# Cuándo se ejecutará el workflow
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

# Definir los trabajos (jobs)
jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # 1. Clonar el repositorio
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Configurar PHP
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.0' 
          extensions: mbstring, dom, pdo, pdo_mysql # Agrega las extensiones necesarias
          ini-values: post_max_size=256M, upload_max_filesize=256M
          coverage: none 

      # 3. Instalar dependencias con Composer
      - name: Install Composer dependencies
        run: composer install --no-progress --no-suggest

      # 4. Configurar el entorno de pruebas
      - name: Set up environment
        run: cp .env.example .env

      # 5. Ejecutar las pruebas con PHPUnit
      - name: Run PHPUnit tests
        run: ./vendor/bin/phpunit
